[project]
name = "pylandax"
version = "1.0.0"
description = "Landax client"
authors = [{ name = "David Skoland", email = "david.skoland@asterisk.digital" }]
requires-python = ">=3.13"

readme = "README.md"
license = { text = "MIT" }

dependencies = [
    "requests==2.33.1",
    "pydantic==2.12.5",
]

[dependency-groups]
dev = [
    "python-dotenv==1.2.2",
    "ruff==0.15.7",
    "tox==4.50.3",
    "tox-uv==1.33.4",
    "pytest==9.0.3"
]

[build-system]
requires = ["setuptools>=75", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.tox]
env_list = ["py313", "py314"]

[tool.tox.env_run_base]
dependency_groups = ["dev"]
commands = [["pytest"]]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["pylandax*"]

[tool.setuptools.package-data]
pylandax = ["*.json"]
